/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package QuanLyTHuVien;

import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form GiaoDienChinh
     */
    DefaultTableModel dtm;
    DefaultTableModel dtmdg;
    DefaultTableModel dtmmts;
    DefaultTableModel dtmmtscopy;
    DefaultTableModel dtmtks;
    DefaultTableModel dtmqlt;
    DefaultTableModel dtmtkdg;

    Connection conn = null;
    ResultSet rs = null;
    Statement stm = null;

    public GiaoDienChinh() {
        initComponents();
        setVisible(true);
        setLocation(200, 100);
        setTitle("CHƯƠNG TRÌNH QUẢN LÝ SÁCH TRONG THƯ VIỆN TRƯỜNG ĐẠI HỌC CÔNG NGHIỆP HÀ NỘI");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        txtngaysinh.setToolTipText("yyyy-MM-dd");
        txtidsach.requestFocus();
        dtm = (DefaultTableModel) tbsach.getModel();
        dtmdg = (DefaultTableModel) tbdocgia.getModel();
        dtmmts = (DefaultTableModel) tbmuontra.getModel();
        dtmmtscopy = (DefaultTableModel) tbmuontrasachcopy.getModel();
        dtmtks = (DefaultTableModel) tbthongkesach.getModel();
        dtmqlt = (DefaultTableModel) tbthe.getModel();
        dtmtkdg = (DefaultTableModel) tbthongkedocgia.getModel();

    }

    public Connection getConnect() {
        try {
            String url = "jdbc:derby://localhost:1527/QuanLyThuVien";
            String user = "root";
            String pass = "123456";
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            System.out.println("kết nối thành công database với tài khoản " + user);
            return DriverManager.getConnection(url, user, pass);
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, "Khong the ket noi voi database \n" + e);
        }
        return null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        buttonGroupQLSach = new javax.swing.ButtonGroup();
        buttonGroupQLDocGia = new javax.swing.ButtonGroup();
        buttonGroupQLMuonTraSach = new javax.swing.ButtonGroup();
        buttonGroupQLThe = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtidsach = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttensach = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttacgia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txttheloai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtgiasach = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnxb = new javax.swing.JTextField();
        btntimkiemsach = new javax.swing.JButton();
        rbtensach = new javax.swing.JRadioButton();
        rbtacgia = new javax.swing.JRadioButton();
        rbtheloai = new javax.swing.JRadioButton();
        btnthemsach = new javax.swing.JButton();
        btnxoasach = new javax.swing.JButton();
        btnsuasach = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbsach = new javax.swing.JTable();
        btnhuysach = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtvitri = new javax.swing.JTextField();
        rbgia = new javax.swing.JRadioButton();
        btnhienthibangsach = new javax.swing.JButton();
        rbidsach = new javax.swing.JRadioButton();
        rbvitri = new javax.swing.JRadioButton();
        btnthoatsach = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtiddocgia = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txthoten = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtngaysinh = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtnghenghiep = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JTextField();
        btntimkiemdocgia = new javax.swing.JButton();
        rbhoten = new javax.swing.JRadioButton();
        rbiddocgia = new javax.swing.JRadioButton();
        rbsdt = new javax.swing.JRadioButton();
        btnthemdocgia = new javax.swing.JButton();
        btnsuadocgia = new javax.swing.JButton();
        btnxoadocgia = new javax.swing.JButton();
        btnhuydocgia = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbdocgia = new javax.swing.JTable();
        btnthoatdocgia = new javax.swing.JButton();
        btnhienthidocgia = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtidthe = new javax.swing.JTextField();
        txthotenthe = new javax.swing.JTextField();
        btnthemthe = new javax.swing.JButton();
        btnsuathe = new javax.swing.JButton();
        btnxoathe = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbthe = new javax.swing.JTable();
        btntimkiemthe = new javax.swing.JButton();
        btnhuythe = new javax.swing.JButton();
        btnthoatthe = new javax.swing.JButton();
        rbidthe = new javax.swing.JRadioButton();
        rbhotenthe = new javax.swing.JRadioButton();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        txtngaycap = new javax.swing.JTextField();
        txthethan = new javax.swing.JTextField();
        btnhienthithe = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtiddocgiaqlmuontra = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txthotenqlmuontra = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtidsachqlmuontra = new javax.swing.JTextField();
        btnthemqlmuontra = new javax.swing.JButton();
        btnsuaqlmuontra = new javax.swing.JButton();
        btnxoaqlmuontra = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txttensachqlmuontra = new javax.swing.JTextField();
        txtngaymuon = new javax.swing.JTextField();
        txtngayhentra = new javax.swing.JTextField();
        txtngaythuctra = new javax.swing.JTextField();
        btntimkiemqlmuontra = new javax.swing.JButton();
        rbiddocgiaqlmuontra = new javax.swing.JRadioButton();
        rbidsachqlmuontra = new javax.swing.JRadioButton();
        btnhuyqlmuontra = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbmuontra = new javax.swing.JTable();
        btnthoatqlmuontra = new javax.swing.JButton();
        btnhienthiqlmuontra = new javax.swing.JButton();
        rbidsachvaiddocgiaqlmuontra = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        btncapnhatthongkesach = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbthongkesach = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lbsachcon = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txttheloaithongkesach = new javax.swing.JTextField();
        lbsoluongsachtheotheloai = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbmuontrasachcopy = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txttungay = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtdenngay = new javax.swing.JTextField();
        btncapnhatthongkedocgia = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        tbthongkedocgia = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("ID sách");

        txtidsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidsachActionPerformed(evt);
            }
        });

        jLabel4.setText("Tên sách");

        jLabel5.setText("Tác giả");

        jLabel1.setText("Số lượng");

        jLabel2.setText("Thể loại");

        jLabel6.setText("Giá sách");

        jLabel7.setText("Nhà xuất bản");

        btntimkiemsach.setText("Tìm kiếm");
        btntimkiemsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemsachActionPerformed(evt);
            }
        });

        buttonGroupQLSach.add(rbtensach);
        rbtensach.setText("Theo tên sách");

        buttonGroupQLSach.add(rbtacgia);
        rbtacgia.setText("Theo tác giả");

        buttonGroupQLSach.add(rbtheloai);
        rbtheloai.setText("Theo thể loại");

        btnthemsach.setText("Thêm");
        btnthemsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemsachActionPerformed(evt);
            }
        });

        btnxoasach.setText("Xóa");
        btnxoasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoasachActionPerformed(evt);
            }
        });

        btnsuasach.setText("Sửa");
        btnsuasach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuasachActionPerformed(evt);
            }
        });

        tbsach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID sách", "Tên sách", "Tác giả", "Số lượng", "Thể loại", "Giá sách", "NXB", "Vị trí"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbsach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbsachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbsach);

        btnhuysach.setText("Hủy");
        btnhuysach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuysachActionPerformed(evt);
            }
        });

        jLabel14.setText("Vị trí");

        buttonGroupQLSach.add(rbgia);
        rbgia.setText("Theo giá");

        btnhienthibangsach.setText("Load All");
        btnhienthibangsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhienthibangsachActionPerformed(evt);
            }
        });

        buttonGroupQLSach.add(rbidsach);
        rbidsach.setText("ID sách");

        buttonGroupQLSach.add(rbvitri);
        rbvitri.setText("Theo vị trí");

        btnthoatsach.setText("Thoát");
        btnthoatsach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatsachActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(32, 32, 32)
                                .addComponent(txtidsach, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel1))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txttacgia)
                                    .addComponent(txttensach, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtsoluong, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnhienthibangsach)
                                .addGap(18, 18, 18)
                                .addComponent(btnthemsach)
                                .addGap(18, 18, 18)
                                .addComponent(btnxoasach)
                                .addGap(18, 18, 18)
                                .addComponent(btnsuasach)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtvitri, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtnxb, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtgiasach, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(68, 68, 68)
                                    .addComponent(txttheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbidsach)
                                .addGap(10, 10, 10)
                                .addComponent(rbtensach)
                                .addGap(18, 18, 18)
                                .addComponent(rbtacgia)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnhuysach)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(rbtheloai)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbgia))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btntimkiemsach)
                                .addGap(183, 183, 183)
                                .addComponent(btnthoatsach)))
                        .addGap(18, 18, 18)
                        .addComponent(rbvitri)
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtidsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txttheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txttensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtgiasach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txttacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtnxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(txtvitri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnhienthibangsach)
                    .addComponent(btnthemsach)
                    .addComponent(btnxoasach)
                    .addComponent(btnsuasach)
                    .addComponent(btntimkiemsach)
                    .addComponent(btnhuysach)
                    .addComponent(btnthoatsach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtensach)
                    .addComponent(rbtacgia)
                    .addComponent(rbtheloai)
                    .addComponent(rbgia)
                    .addComponent(rbidsach)
                    .addComponent(rbvitri))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý sách", jPanel1);

        jLabel8.setText("ID độc giả");

        jLabel9.setText("Họ tên");

        jLabel10.setText("Ngày sinh");

        jLabel11.setText("Địa chỉ");

        jLabel12.setText("Nghề nghiệp");

        jLabel13.setText("Số điện thoại");

        btntimkiemdocgia.setText("Tìm kiếm");
        btntimkiemdocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemdocgiaActionPerformed(evt);
            }
        });

        buttonGroupQLDocGia.add(rbhoten);
        rbhoten.setText("Theo họ tên");

        buttonGroupQLDocGia.add(rbiddocgia);
        rbiddocgia.setText("Theo ID");

        buttonGroupQLDocGia.add(rbsdt);
        rbsdt.setText("Theo SĐT");

        btnthemdocgia.setText("Thêm");
        btnthemdocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemdocgiaActionPerformed(evt);
            }
        });

        btnsuadocgia.setText("Sửa");
        btnsuadocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuadocgiaActionPerformed(evt);
            }
        });

        btnxoadocgia.setText("Xóa");
        btnxoadocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoadocgiaActionPerformed(evt);
            }
        });

        btnhuydocgia.setText("Hủy");
        btnhuydocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuydocgiaActionPerformed(evt);
            }
        });

        tbdocgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID độc giả", "Họ tên", "Ngày sinh", "Địa chỉ", "Nghề nghiệp", "Số điện thoại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbdocgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbdocgiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbdocgia);

        btnthoatdocgia.setText("Thoát");
        btnthoatdocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatdocgiaActionPerformed(evt);
            }
        });

        btnhienthidocgia.setText("Load All");
        btnhienthidocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhienthidocgiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(33, 33, 33)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtiddocgia, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                                    .addComponent(txthoten)
                                    .addComponent(txtngaysinh))
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(btnhienthidocgia)
                                .addGap(18, 18, 18)
                                .addComponent(btnthemdocgia)
                                .addGap(18, 18, 18)
                                .addComponent(btnsuadocgia)
                                .addGap(18, 18, 18)
                                .addComponent(btnxoadocgia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btntimkiemdocgia)
                                .addGap(18, 18, 18)
                                .addComponent(rbiddocgia)
                                .addGap(18, 18, 18)
                                .addComponent(rbhoten)
                                .addGap(18, 18, 18)
                                .addComponent(rbsdt)
                                .addGap(18, 18, 18)
                                .addComponent(btnhuydocgia)
                                .addGap(18, 18, 18)
                                .addComponent(btnthoatdocgia))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(38, 38, 38)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnghenghiep, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                                    .addComponent(txtsdt)
                                    .addComponent(txtdiachi))))
                        .addContainerGap(81, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtiddocgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txthoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(txtnghenghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbhoten)
                    .addComponent(rbsdt)
                    .addComponent(btnthemdocgia)
                    .addComponent(btnsuadocgia)
                    .addComponent(btnxoadocgia)
                    .addComponent(btnhuydocgia)
                    .addComponent(btntimkiemdocgia)
                    .addComponent(btnthoatdocgia)
                    .addComponent(rbiddocgia)
                    .addComponent(btnhienthidocgia))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý độc giả", jPanel2);

        jLabel23.setText("ID thẻ");

        jLabel24.setText("Họ tên");

        btnthemthe.setText("Thêm");
        btnthemthe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemtheActionPerformed(evt);
            }
        });

        btnsuathe.setText("Sửa");
        btnsuathe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuatheActionPerformed(evt);
            }
        });

        btnxoathe.setText("Xóa");
        btnxoathe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoatheActionPerformed(evt);
            }
        });

        tbthe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID thẻ", "Họ tên", "Ngày cấp", "Hết hạn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbthe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbtheMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbthe);

        btntimkiemthe.setText("Tìm kiếm");
        btntimkiemthe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemtheActionPerformed(evt);
            }
        });

        btnhuythe.setText("Hủy");
        btnhuythe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuytheActionPerformed(evt);
            }
        });

        btnthoatthe.setText("Thoát");
        btnthoatthe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoattheActionPerformed(evt);
            }
        });

        buttonGroupQLThe.add(rbidthe);
        rbidthe.setText("Theo ID");

        buttonGroupQLThe.add(rbhotenthe);
        rbhotenthe.setText("Theo họ tên");

        jLabel27.setText("Ngày cấp");

        jLabel28.setText("Hết hạn");

        btnhienthithe.setText("Load All");
        btnhienthithe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhienthitheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1126, Short.MAX_VALUE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btnhienthithe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(btnthemthe)
                        .addGap(18, 18, 18)
                        .addComponent(btnsuathe)
                        .addGap(18, 18, 18)
                        .addComponent(btnxoathe)
                        .addGap(12, 12, 12))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtidthe)
                            .addComponent(txthotenthe, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txthethan, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                            .addComponent(txtngaycap)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btntimkiemthe)
                        .addGap(18, 18, 18)
                        .addComponent(rbidthe)
                        .addGap(18, 18, 18)
                        .addComponent(rbhotenthe)
                        .addGap(18, 18, 18)
                        .addComponent(btnhuythe)
                        .addGap(18, 18, 18)
                        .addComponent(btnthoatthe)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(txtidthe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(txtngaycap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(txthotenthe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(txthethan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemthe)
                    .addComponent(btnsuathe)
                    .addComponent(btnxoathe)
                    .addComponent(btnhuythe)
                    .addComponent(btntimkiemthe)
                    .addComponent(btnthoatthe)
                    .addComponent(rbidthe)
                    .addComponent(rbhotenthe)
                    .addComponent(btnhienthithe))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý thẻ thư viện", jPanel3);

        jLabel16.setText("ID độc giả");

        jLabel17.setText("Họ tên");

        jLabel18.setText("ID sách");

        btnthemqlmuontra.setText("Thêm");
        btnthemqlmuontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemqlmuontraActionPerformed(evt);
            }
        });

        btnsuaqlmuontra.setText("Sửa");
        btnsuaqlmuontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaqlmuontraActionPerformed(evt);
            }
        });

        btnxoaqlmuontra.setText("Xóa");
        btnxoaqlmuontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaqlmuontraActionPerformed(evt);
            }
        });

        jLabel19.setText("Tên sách");

        jLabel20.setText("Ngày mượn");

        jLabel21.setText("Ngày hẹn trả");

        jLabel22.setText("Ngày thực trả");

        btntimkiemqlmuontra.setText("Tìm kiếm");
        btntimkiemqlmuontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimkiemqlmuontraActionPerformed(evt);
            }
        });

        buttonGroupQLMuonTraSach.add(rbiddocgiaqlmuontra);
        rbiddocgiaqlmuontra.setText("Theo ID độc giả");

        buttonGroupQLMuonTraSach.add(rbidsachqlmuontra);
        rbidsachqlmuontra.setText("Theo ID sách");

        btnhuyqlmuontra.setText("Hủy");
        btnhuyqlmuontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyqlmuontraActionPerformed(evt);
            }
        });

        tbmuontra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID độc giả", "Họ tên", "ID sách", "Tên sách", "Ngày mượn", "Ngày hẹn trả", "Ngày thực trả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbmuontra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbmuontraMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbmuontra);

        btnthoatqlmuontra.setText("Thoát");
        btnthoatqlmuontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthoatqlmuontraActionPerformed(evt);
            }
        });

        btnhienthiqlmuontra.setText("Load All");
        btnhienthiqlmuontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhienthiqlmuontraActionPerformed(evt);
            }
        });

        buttonGroupQLMuonTraSach.add(rbidsachvaiddocgiaqlmuontra);
        rbidsachvaiddocgiaqlmuontra.setText("Theo ID sách và id độc giả");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(btnhienthiqlmuontra)
                            .addComponent(jLabel19))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtiddocgiaqlmuontra)
                            .addComponent(txthotenqlmuontra)
                            .addComponent(txtidsachqlmuontra)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(btnthemqlmuontra)
                                .addGap(27, 27, 27)
                                .addComponent(btnsuaqlmuontra)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(btnxoaqlmuontra))
                            .addComponent(txttensachqlmuontra))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(rbidsachvaiddocgiaqlmuontra)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(btntimkiemqlmuontra))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtngayhentra, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                                .addComponent(txtngaythuctra))
                            .addComponent(txtngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(rbiddocgiaqlmuontra)
                        .addGap(18, 18, 18)
                        .addComponent(rbidsachqlmuontra)
                        .addGap(18, 18, 18)
                        .addComponent(btnhuyqlmuontra)
                        .addGap(18, 18, 18)
                        .addComponent(btnthoatqlmuontra)))
                .addContainerGap(226, Short.MAX_VALUE))
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addGap(107, 107, 107))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtiddocgiaqlmuontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel17)
                    .addComponent(txthotenqlmuontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtngaymuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txtngayhentra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtidsachqlmuontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(txtngaythuctra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(txttensachqlmuontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthemqlmuontra)
                    .addComponent(btnsuaqlmuontra)
                    .addComponent(btnxoaqlmuontra)
                    .addComponent(btntimkiemqlmuontra)
                    .addComponent(btnhienthiqlmuontra))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbiddocgiaqlmuontra)
                    .addComponent(rbidsachqlmuontra)
                    .addComponent(btnhuyqlmuontra)
                    .addComponent(btnthoatqlmuontra)
                    .addComponent(rbidsachvaiddocgiaqlmuontra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quản lý mượn trả sách", jPanel5);

        btncapnhatthongkesach.setText("Cập nhật");
        btncapnhatthongkesach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatthongkesachActionPerformed(evt);
            }
        });

        tbthongkesach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID sách", "Tên sách", "Tác giả", "Số lượng", "Giá sách", "Thể loại", "NXB", "Số lượng mượn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tbthongkesach);

        jLabel25.setText("Số lượng sách còn trong thư viện:  ");

        jLabel26.setText("Bảng thống kê sách mượn nhiều:");

        lbsachcon.setText("0");

        jLabel15.setText("Số lượng sách theo thể loại:");

        txttheloaithongkesach.setText("Van hoc");

        lbsoluongsachtheotheloai.setText("0");

        jLabel29.setText("(Cuốn).");

        jLabel30.setText("(Cuốn).");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1111, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btncapnhatthongkesach)
                        .addGap(172, 172, 172)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbsachcon, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txttheloaithongkesach, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbsoluongsachtheotheloai, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lbsachcon)
                    .addComponent(jLabel29)
                    .addComponent(btncapnhatthongkesach))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txttheloaithongkesach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30)
                    .addComponent(lbsoluongsachtheotheloai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Thống kê sách", jPanel6);

        tbmuontrasachcopy.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID độc giả", "Họ tên", "ID sách", "Tên sách", "Ngày mượn", "Ngày hẹn trả", "Ngày thực trả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tbmuontrasachcopy);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(295, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(189, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Bảng lưu thông tin mượn trả sách", jPanel8);

        jLabel31.setText("Bảng thống kế độc giả quá hạn từ ngày(yyyy-MM-dd)");

        jLabel32.setText("đến ngày");

        btncapnhatthongkedocgia.setText("Cập nhật");
        btncapnhatthongkedocgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncapnhatthongkedocgiaActionPerformed(evt);
            }
        });

        tbthongkedocgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID độc giả", "Họ tên", "ID sách", "Tên sách", "Ngày mượn", "Ngày hẹn trả", "Ngày thực trả"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tbthongkedocgia);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 849, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncapnhatthongkedocgia)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(18, 18, 18)
                        .addComponent(txttungay, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel32)
                        .addGap(18, 18, 18)
                        .addComponent(txtdenngay, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(248, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(txttungay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32)
                    .addComponent(txtdenngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btncapnhatthongkedocgia)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Thống kê độc giả quá hạn", jPanel7);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1131, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//========================================QUẢN LÝ SÁCH==================================================

    private void btnhienthibangsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhienthibangsachActionPerformed

    }//GEN-LAST:event_btnhienthibangsachActionPerformed

    private void btnxoasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoasachActionPerformed

    }//GEN-LAST:event_btnxoasachActionPerformed

    private void btnthemsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemsachActionPerformed

    }//GEN-LAST:event_btnthemsachActionPerformed

    private void btntimkiemsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemsachActionPerformed

    }//GEN-LAST:event_btntimkiemsachActionPerformed

    private void btnsuasachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuasachActionPerformed

    }//GEN-LAST:event_btnsuasachActionPerformed

    private void tbsachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbsachMouseClicked
        int row = tbsach.getSelectedRow();
        String idSach = (String) tbsach.getValueAt(row, 0);
        String tenSach = (String) tbsach.getValueAt(row, 1);
        String tacGia = (String) tbsach.getValueAt(row, 2);
        String soLuong = (String) tbsach.getValueAt(row, 3);
        String theLoai = (String) tbsach.getValueAt(row, 4);
        String giaSach = (String) tbsach.getValueAt(row, 5);
        String nhaXuatBan = (String) tbsach.getValueAt(row, 6);
        String viTri = (String) tbsach.getValueAt(row, 7);
        txtidsach.setText(idSach);
        txttensach.setText(tenSach);
        txttacgia.setText(tacGia);
        txtsoluong.setText(soLuong);
        txttheloai.setText(theLoai);
        txtgiasach.setText(giaSach);
        txtnxb.setText(nhaXuatBan);
        txtvitri.setText(viTri);
    }//GEN-LAST:event_tbsachMouseClicked

    private void btnthoatsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatsachActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnthoatsachActionPerformed

    private void btnhuysachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuysachActionPerformed
        txtidsach.setText("");
        txttensach.setText("");
        txttacgia.setText("");
        txtsoluong.setText("");
        txttheloai.setText("");
        txtgiasach.setText("");
        txtnxb.setText("");
        txtvitri.setText("");
    }//GEN-LAST:event_btnhuysachActionPerformed

//===========================================QUẢN LÝ ĐỘC GIẢ=================================================

    private void btnhienthidocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhienthidocgiaActionPerformed

    }//GEN-LAST:event_btnhienthidocgiaActionPerformed

    private void btnthemdocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemdocgiaActionPerformed

    }//GEN-LAST:event_btnthemdocgiaActionPerformed

    private void tbdocgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbdocgiaMouseClicked
        int row = tbdocgia.getSelectedRow();

        String idDocGia = (String) dtmdg.getValueAt(row, 0);
        String hoTen = (String) dtmdg.getValueAt(row, 1);
        String ngaySinh = (String) dtmdg.getValueAt(row, 2);
        String diaChi = (String) dtmdg.getValueAt(row, 3);
        String ngheNghiep = (String) dtmdg.getValueAt(row, 4);
        String sdt = (String) dtmdg.getValueAt(row, 5);

        txtiddocgia.setText(idDocGia);
        txthoten.setText(hoTen);
        txtngaysinh.setText(ngaySinh);
        txtdiachi.setText(diaChi);
        txtnghenghiep.setText(ngheNghiep);
        txtsdt.setText(sdt);
    }//GEN-LAST:event_tbdocgiaMouseClicked

    private void btnsuadocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuadocgiaActionPerformed

    }//GEN-LAST:event_btnsuadocgiaActionPerformed

    private void btnxoadocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoadocgiaActionPerformed

    }//GEN-LAST:event_btnxoadocgiaActionPerformed

    private void btntimkiemdocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemdocgiaActionPerformed

    }//GEN-LAST:event_btntimkiemdocgiaActionPerformed

    private void btnhuydocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuydocgiaActionPerformed
        txtiddocgia.setText("");
        txthoten.setText("");
        txtngaysinh.setText("");
        txtnghenghiep.setText("");
        txtsdt.setText("");
        txtdiachi.setText("");
    }//GEN-LAST:event_btnhuydocgiaActionPerformed

    private void btnthoatdocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatdocgiaActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnthoatdocgiaActionPerformed

//=================================QUẢN LÝ MƯỢN TRẢ SÁCH=================================================

    private void btnhienthiqlmuontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhienthiqlmuontraActionPerformed

        try {
            conn = getConnect();
            DefaultTableModel model = (DefaultTableModel) tbmuontra.getModel();
            model.setRowCount(0);
            stm = conn.createStatement();
            String sql = "SELECT *FROM MUONTRASACH";
            ResultSet rs = stm.executeQuery(sql);
            while (rs.next()) {
                String idDocGia = rs.getString("IDDOCGIA");
                String hoTen = rs.getString("HOTEN");
                String idSach = rs.getString("IDSACH");
                String tenSach = rs.getString("TENSACH");
                Date ngayMuon = rs.getDate("NGAYMUON");
                Date ngayHetHan = rs.getDate("NGAYHETHAN");
                Date ngayThucTra = rs.getDate("NGAYTHUCTRA");
                model.addRow(new Object[]{
                    idDocGia, hoTen, idSach, tenSach, ngayMuon, ngayHetHan, ngayThucTra
                });
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btnhienthiqlmuontraActionPerformed

    private void btnthemqlmuontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemqlmuontraActionPerformed

    }//GEN-LAST:event_btnthemqlmuontraActionPerformed

    private void btnsuaqlmuontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaqlmuontraActionPerformed

    }//GEN-LAST:event_btnsuaqlmuontraActionPerformed

    private void tbmuontraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmuontraMouseClicked
        int row = tbmuontra.getSelectedRow();
        String idDocGia = (String) dtmmts.getValueAt(row, 0);
        String hoTen = (String) dtmmts.getValueAt(row, 1);
        String idSach = (String) dtmmts.getValueAt(row, 2);
        String tenSach = (String) dtmmts.getValueAt(row, 3);
        String ngayMuon = dtmmts.getValueAt(row, 4).toString();
        String ngayHenTra = dtmmts.getValueAt(row, 5).toString();
        String ngayThucTra = (String) dtmmts.getValueAt(row, 6);

        txtiddocgiaqlmuontra.setText(idDocGia);
        txthotenqlmuontra.setText(hoTen);
        txtidsachqlmuontra.setText(idSach);
        txttensachqlmuontra.setText(tenSach);
        txtngaymuon.setText(ngayMuon);
        txtngayhentra.setText(ngayHenTra);
        txtngaythuctra.setText(ngayThucTra);
    }//GEN-LAST:event_tbmuontraMouseClicked

    private void btnxoaqlmuontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaqlmuontraActionPerformed

    }//GEN-LAST:event_btnxoaqlmuontraActionPerformed

    private void btnhuyqlmuontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyqlmuontraActionPerformed
        txtiddocgiaqlmuontra.setText("");
        txthotenqlmuontra.setText("");
        txtidsachqlmuontra.setText("");
        txttensachqlmuontra.setText("");
        txtngaymuon.setText("");
        txtngayhentra.setText("");
        txtngaythuctra.setText("");
    }//GEN-LAST:event_btnhuyqlmuontraActionPerformed

    private void btnthoatqlmuontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoatqlmuontraActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnthoatqlmuontraActionPerformed

    private void btntimkiemqlmuontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemqlmuontraActionPerformed

    }//GEN-LAST:event_btntimkiemqlmuontraActionPerformed

    private void btncapnhatthongkesachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatthongkesachActionPerformed

    }//GEN-LAST:event_btncapnhatthongkesachActionPerformed

//==============================================QUẢN LÝ THẺ THƯ VIỆN================================================================
    public void loadDataQLThe() {
        try {
            dtmqlt.setRowCount(0);
            stm = conn.createStatement();
            String q = "SELECT * FROM THETHUVIEN";
            ResultSet rs = stm.executeQuery(q);
            while (rs.next()) {
                String idThe = rs.getString("idThe");
                String hoTen = rs.getString("hoTen");
                Date ngayCap = rs.getDate("ngayCap");
                Date ngayHetHan = rs.getDate("ngayHetHan");
                dtmqlt.addRow(new Object[]{
                    idThe, hoTen, ngayCap, ngayHetHan
                });
            }
            conn.close();
        } catch (Exception e) {
            System.out.println("Có lỗi xảy ra!!! " + e.getMessage());
        }
    }
    private void btnhienthitheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhienthitheActionPerformed
        conn = getConnect();
        loadDataQLThe();
    }//GEN-LAST:event_btnhienthitheActionPerformed

    private void btnthemtheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemtheActionPerformed
        conn = getConnect();
        String sql = "INSERT INTO THETHUVIEN(idThe,hoTen,ngayCap,ngayHetHan) VALUES(?,?,?,?)";
        try {
            PreparedStatement pre = conn.prepareStatement("insert into THETHUVIEN values (?,?,?,?)");
            pre.setString(1, txtidthe.getText());
            pre.setString(2, txthotenthe.getText());
            pre.setString(3, txtngaycap.getText());
            pre.setString(4, txthethan.getText());
            pre.executeUpdate();
            loadDataQLThe();
            conn.close();

        } catch (Exception ex) {
            System.out.println("Lỗi");
        }
    }//GEN-LAST:event_btnthemtheActionPerformed

    private void btnsuatheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuatheActionPerformed
        conn = getConnect();
        String sql = "UPDATE THETHUVIEN SET hoTen=?," + "ngayCap=?," + "ngayHetHan=?" + "WHERE idThe=?";
        try {
            PreparedStatement pre = conn.prepareStatement("update THETHUVIEN set hoTen=?,ngayCap=?,ngayHetHan=? where idThe=?");
            pre.setString(4, txtidthe.getText());
            pre.setString(1, txthotenthe.getText());
            pre.setString(2, txtngaycap.getText());
            pre.setString(3, txthethan.getText());
            pre.executeUpdate();
            loadDataQLThe();
            conn.close();
        } catch (Exception ex) {
            System.out.println("Lỗi");
        }
    }//GEN-LAST:event_btnsuatheActionPerformed

    private void btnxoatheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoatheActionPerformed
        conn = getConnect();
        String sql = "DELETE FROM THETHUVIEN WHERE idThe=?";
        try {
            PreparedStatement pre = conn.prepareStatement("DELETE FROM THETHUVIEN WHERE idThe=?");
            pre.setString(1, txtidthe.getText());
            pre.executeUpdate();
            loadDataQLThe();
            conn.close();
        } catch (Exception e) {
            System.out.println("Lỗi");
        }
    }//GEN-LAST:event_btnxoatheActionPerformed

    private void tbtheMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbtheMouseClicked
        int row = tbthe.getSelectedRow();
        String idthe = (String) tbthe.getValueAt(row, 0);
        String hoten = (String) tbthe.getValueAt(row, 1);
        String ngaycap = tbthe.getValueAt(row, 2).toString();
//        DateFormat dateFormat = new SimpleDateFormat("yyyy-mm-dd"); 
//        String ngaycap = dateFormat.format(tbthe.getValueAt(row, 2));
        String hethan = tbthe.getValueAt(row, 3).toString();
//        String hethan = dateFormat.format(tbthe.getValueAt(row, 3));
        txtidthe.setText(idthe);
        txthotenthe.setText(hoten);
        txtngaycap.setText(ngaycap);
        txthethan.setText(hethan);
    }//GEN-LAST:event_tbtheMouseClicked

    private void btntimkiemtheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimkiemtheActionPerformed
        conn = getConnect();
        dtmqlt.setRowCount(0);
        if (rbidthe.isSelected()) {
            String sql = "SELECT * FROM THETHUVIEN WHERE idTHE =?";
            try {
                PreparedStatement pre = conn.prepareStatement("SELECT * FROM THETHUVIEN WHERE idTHE =?");
                pre.setString(1, txtidthe.getText());
                ResultSet rs = pre.executeQuery();
                while (rs.next()) {
                    String idThe = rs.getString("idThe");
                    String hoTen = rs.getString("hoTen");
                    Date ngayCap = rs.getDate("ngayCap");
                    Date ngayHetHan = rs.getDate("ngayHetHan");
                    
                    dtmqlt.addRow(new Object[]{
                        idThe, hoTen, ngayCap, ngayHetHan
                    });
                }
                conn.close();
            } catch (Exception e) {
                System.out.println("Lỗi!!!");
            }finally{
                return;
            }
        }
        String sql = "SELECT * FROM THETHUVIEN WHERE hoTen =?";
            try {
                PreparedStatement pre = conn.prepareStatement("SELECT * FROM THETHUVIEN WHERE hoTen =?");
                pre.setString(1, txthotenthe.getText());
                ResultSet rs = pre.executeQuery();
                while (rs.next()) {
                    String idThe = rs.getString("idThe");
                    String hoTen = rs.getString("hoTen");
                    Date ngayCap = rs.getDate("ngayCap");
                    Date ngayHetHan = rs.getDate("ngayHetHan");
                    
                    dtmqlt.addRow(new Object[]{
                        idThe, hoTen, ngayCap, ngayHetHan
                    });
                }
                conn.close();
            } catch (Exception e) {
                System.out.println("Lỗi!!!");
            }
    }//GEN-LAST:event_btntimkiemtheActionPerformed

    private void btnhuytheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuytheActionPerformed
        txtidthe.setText("");
        txthotenthe.setText("");
        txtngaycap.setText("");
        txthethan.setText("");
    }//GEN-LAST:event_btnhuytheActionPerformed

    private void btnthoattheActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthoattheActionPerformed
        int kt = JOptionPane.showConfirmDialog(rootPane, "Bạn có chắc chắn muốn xóa thông tin này không?", "Thông báo", JOptionPane.YES_NO_OPTION);
        if(kt == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnthoattheActionPerformed

//===================================================THỐNG KÊ ĐỘC GIẢ QUÁ HẠN======================================================
    private void btncapnhatthongkedocgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncapnhatthongkedocgiaActionPerformed

    }//GEN-LAST:event_btncapnhatthongkedocgiaActionPerformed

    private void txtidsachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidsachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidsachActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncapnhatthongkedocgia;
    private javax.swing.JButton btncapnhatthongkesach;
    private javax.swing.JButton btnhienthibangsach;
    private javax.swing.JButton btnhienthidocgia;
    private javax.swing.JButton btnhienthiqlmuontra;
    private javax.swing.JButton btnhienthithe;
    private javax.swing.JButton btnhuydocgia;
    private javax.swing.JButton btnhuyqlmuontra;
    private javax.swing.JButton btnhuysach;
    private javax.swing.JButton btnhuythe;
    private javax.swing.JButton btnsuadocgia;
    private javax.swing.JButton btnsuaqlmuontra;
    private javax.swing.JButton btnsuasach;
    private javax.swing.JButton btnsuathe;
    private javax.swing.JButton btnthemdocgia;
    private javax.swing.JButton btnthemqlmuontra;
    private javax.swing.JButton btnthemsach;
    private javax.swing.JButton btnthemthe;
    private javax.swing.JButton btnthoatdocgia;
    private javax.swing.JButton btnthoatqlmuontra;
    private javax.swing.JButton btnthoatsach;
    private javax.swing.JButton btnthoatthe;
    private javax.swing.JButton btntimkiemdocgia;
    private javax.swing.JButton btntimkiemqlmuontra;
    private javax.swing.JButton btntimkiemsach;
    private javax.swing.JButton btntimkiemthe;
    private javax.swing.JButton btnxoadocgia;
    private javax.swing.JButton btnxoaqlmuontra;
    private javax.swing.JButton btnxoasach;
    private javax.swing.JButton btnxoathe;
    private javax.swing.ButtonGroup buttonGroupQLDocGia;
    private javax.swing.ButtonGroup buttonGroupQLMuonTraSach;
    private javax.swing.ButtonGroup buttonGroupQLSach;
    private javax.swing.ButtonGroup buttonGroupQLThe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbsachcon;
    private javax.swing.JLabel lbsoluongsachtheotheloai;
    private javax.swing.JRadioButton rbgia;
    private javax.swing.JRadioButton rbhoten;
    private javax.swing.JRadioButton rbhotenthe;
    private javax.swing.JRadioButton rbiddocgia;
    private javax.swing.JRadioButton rbiddocgiaqlmuontra;
    private javax.swing.JRadioButton rbidsach;
    private javax.swing.JRadioButton rbidsachqlmuontra;
    private javax.swing.JRadioButton rbidsachvaiddocgiaqlmuontra;
    private javax.swing.JRadioButton rbidthe;
    private javax.swing.JRadioButton rbsdt;
    private javax.swing.JRadioButton rbtacgia;
    private javax.swing.JRadioButton rbtensach;
    private javax.swing.JRadioButton rbtheloai;
    private javax.swing.JRadioButton rbvitri;
    private javax.swing.JTable tbdocgia;
    private javax.swing.JTable tbmuontra;
    private javax.swing.JTable tbmuontrasachcopy;
    private javax.swing.JTable tbsach;
    private javax.swing.JTable tbthe;
    private javax.swing.JTable tbthongkedocgia;
    private javax.swing.JTable tbthongkesach;
    private javax.swing.JTextField txtdenngay;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtgiasach;
    private javax.swing.JTextField txthethan;
    private javax.swing.JTextField txthoten;
    private javax.swing.JTextField txthotenqlmuontra;
    private javax.swing.JTextField txthotenthe;
    private javax.swing.JTextField txtiddocgia;
    private javax.swing.JTextField txtiddocgiaqlmuontra;
    private javax.swing.JTextField txtidsach;
    private javax.swing.JTextField txtidsachqlmuontra;
    private javax.swing.JTextField txtidthe;
    private javax.swing.JTextField txtngaycap;
    private javax.swing.JTextField txtngayhentra;
    private javax.swing.JTextField txtngaymuon;
    private javax.swing.JTextField txtngaysinh;
    private javax.swing.JTextField txtngaythuctra;
    private javax.swing.JTextField txtnghenghiep;
    private javax.swing.JTextField txtnxb;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JTextField txttacgia;
    private javax.swing.JTextField txttensach;
    private javax.swing.JTextField txttensachqlmuontra;
    private javax.swing.JTextField txttheloai;
    private javax.swing.JTextField txttheloaithongkesach;
    private javax.swing.JTextField txttungay;
    private javax.swing.JTextField txtvitri;
    // End of variables declaration//GEN-END:variables
}
